version: "3.9"

services:
  web:
    build: .
    container_name: web
    networks:
      - caddy_shared_network
    ports:
      - "8008:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true" 
  webtest:
    profiles:
      - test
    build: .
    ports:
      - "8001:5000" 
    volumes:
      - .:/code
    environment:
      FLASK_APP: "testapp" 
      FLASK_DEBUG: "true" 
  solr:
    image: solr:8
    networks:
      - caddy_shared_network
    ports:
      - "8983:8983"
    volumes:
      - ./solr:/solr-conf
    command:
      - solr-precreate
      - inscriptions
      - /solr-conf

networks:
  caddy_shared_network:
    external: true
