version: "3.9"

services:
  web:
    build: .
    container_name: web_sitefinds
    networks:
      - caddy_shared_network
    ports:
      - "81:80"
    volumes:
      - ./public:/usr/share/nginx/html

networks:
  caddy_shared_network:
    external: true